"""Security analysis, status, alerts, and audit event API endpoints."""

from typing import List, Optional
from fastapi import APIRouter, Query

from app.api.schemas import ResetResponse, SecurityStatusResponse
from app.api.state import app_state
from app.defender.models import (
    SecurityAlert,
    SecurityAnalysisResult,
    SecurityEvent,
)

router = APIRouter(prefix="/security", tags=["Security"])


@router.get("/status", response_model=SecurityStatusResponse)
def get_security_status() -> SecurityStatusResponse:
    """Retrieve high-level organization security status summary."""
    latest = app_state.defender.get_latest_analysis()
    if latest is not None:
        classification = latest.decision.classification
        risk_score = latest.decision.risk_score
        integrity_score = latest.decision.integrity_score
        timestamp = latest.timestamp
    else:
        classification = "NORMAL"
        risk_score = 0.0
        integrity_score = 100.0
        timestamp = None

    active_alerts = len(app_state.defender.get_alerts(active_only=True))

    return SecurityStatusResponse(
        status=classification,
        risk_score=risk_score,
        integrity_score=integrity_score,
        active_alerts=active_alerts,
        sources=5,
        last_analysis_timestamp=timestamp,
        backend_health="ONLINE",
    )


@router.get("/latest", response_model=SecurityAnalysisResult)
def get_latest_security_analysis() -> SecurityAnalysisResult:
    """Retrieve the full, detailed latest multi-stage security analysis result."""
    latest = app_state.defender.get_latest_analysis()
    if latest is None:
        # If no analysis exists yet, analyze current warehouse state
        latest = app_state.defender.analyze(app_state.warehouse.get_current_observation())
    return latest


@router.get("/alerts", response_model=List[SecurityAlert])
def get_security_alerts(
    active_only: bool = Query(default=True, description="Filter for unresolved alerts only")
) -> List[SecurityAlert]:
    """Retrieve security alerts generated by DefenderService."""
    return app_state.defender.get_alerts(active_only=active_only)


@router.get("/events", response_model=List[SecurityEvent])
def get_security_events(
    limit: int = Query(default=50, ge=1, le=500, description="Max number of audit events to return")
) -> List[SecurityEvent]:
    """Retrieve recent security audit events from the timeline."""
    return app_state.defender.get_events(limit=limit)


@router.post("/reset", response_model=ResetResponse)
def reset_security_state() -> ResetResponse:
    """Reset both the warehouse simulator and DefenderService pipeline to baseline state."""
    app_state.reset()
    return ResetResponse(
        success=True,
        message="Simulator and DefenderService successfully reset to initial baseline state.",
    )
